// <auto-generated />
using Examen2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Examen2.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20200311231105_nuevo")]
    partial class nuevo
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2");

            modelBuilder.Entity("Examen2.Models.Llamadas", b =>
                {
                    b.Property<int>("LlamadaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Problema")
                        .HasColumnType("TEXT");

                    b.Property<string>("Solucion")
                        .HasColumnType("TEXT");

                    b.HasKey("LlamadaId");

                    b.ToTable("Llamadas");
                });

            modelBuilder.Entity("Examen2.Models.LlamadasDetalle", b =>
                {
                    b.Property<int>("LlamadasDetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("LlamadaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Problema")
                        .HasColumnType("TEXT");

                    b.Property<string>("Solucion")
                        .HasColumnType("TEXT");

                    b.HasKey("LlamadasDetalleId");

                    b.HasIndex("LlamadaId");

                    b.ToTable("LlamadasDetalles");
                });

            modelBuilder.Entity("Examen2.Models.LlamadasDetalle", b =>
                {
                    b.HasOne("Examen2.Models.Llamadas", null)
                        .WithMany("Detalle")
                        .HasForeignKey("LlamadaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
